[package]
name = "containerd-shim-wws-v1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
containerd-shim = "~0.3"
containerd-shim-wasm = "0.1.1"
wws-config = { git = "https://github.com/vmware-labs/wasm-workers-server", version = "1.1.0" }
wws-server = { git = "https://github.com/vmware-labs/wasm-workers-server", version = "1.1.0" }
wws-router = { git = "https://github.com/vmware-labs/wasm-workers-server", version = "1.1.0" }
log = "~0.4"
tokio = { version = "1", features = [ "full" ] }
tokio-util = { version = "0.6.10", features = [ "codec" ]}
chrono = "~0.4"

[target.x86_64-unknown-linux-musl.dependencies]
openssl = { version = "=0.10.48", features = ["vendored"] }

[target.aarch64-unknown-linux-musl.dependencies]
openssl = { version = "=0.10.48", features = ["vendored"] }